# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=8.0.0+1.21.4
group=com.illusivesoulworks.bedspreads
java_version=21

# Common
minecraft_version=1.21.4
mod_name=Bedspreads
mod_author=Illusive Soulworks
mod_id=bedspreads
license=LGPL-3.0-or-later
issues_url=https://github.com/illusivesoulworks/bedspreads/issues
sources_url=https://github.com/illusivesoulworks/bedspreads
description=Allows players to add banner patterns to their beds!
minecraft_version_range=1.21.4
minecraft_version_range_alt=1.21.4

# Parchment
parchment_mc=1.21.4
parchment_version=2025.03.23

# Fabric
fabric_version=0.119.2+1.21.4
fabric_loader_version=0.16.13

# Forge
forge_version=54.1.0
forge_version_range=[54,)

# NeoForge
neoforge_version=21.4.124
neoforge_version_range=[21.4,)

# Publishing
cf_id=308653
cf_page=https://www.curseforge.com/minecraft/mc-mods/bedspreads
modrinth_id=vNNL5mc7
modrinth_page=https://modrinth.com/mod/bedspreads
release_type=release
release_versions=1.21.4
changelog_link=https://github.com/illusivesoulworks/bedspreads/blob/1.21.4/CHANGELOG.md
discord_thumbnail=https://cdn.modrinth.com/data/vNNL5mc7/ad8c5bcc846d892dda3388d548e928d0ff590ee0.png

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
